// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

const directUrl = process.env["DIRECT_URL"];

if (!directUrl) {
  throw new Error("DIRECT_URL environment variable is required.");
}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directUrl,
  },
};
